### ISSUE TITLE
Delete Supervisor Inspections Slide

### ISSUE THREAD

**Issue by sesquibe** [Datapolitan-Training/parks-intro-analytics#13]
The supervisor inspection "reports" were created specifically for the class, but because we're not using them we don't want to direct people to them so they are no longer on the intranet. Please remove this slide (currently slide 168) and the link to it on the resources slide (currently slide 238).

**Comment by datapolitan** [comment]
Thanks @sesquibe! I'll make sure this gets taken care of.
